### ISSUE TITLE
Error while compiling 2.4 on MacMini M1 running 13.0.1 and Xcode 14.1

### ISSUE THREAD

**Issue by Louis-Demers** [core-plot/core-plot#473]
I get the following error while compiling release 2.4 (latest from git) Universal XCFramework.

```
Prepare build
note: Building targets in dependency order
error: error: accessing build database "/Users/lab/Development/core-plot/build/XCBuildData/build.db": disk I/O error

```
It does appear to generate a framework in `core-plot/build/Release/CorePlot.framework`

**Comment by eskroch** [comment]
Fixed on the `release-2.4` branch. Tested with Xcode 14.2.

**Comment by Louis-Demers** [comment]
Thanks for the rapid response, but tested with a fresh checkout of latest 2.4 with all updated macOS and Xcode, still the same error. Googling seem to indicate it might be due to simultaneous attempts to access the `core-plot/build/XCBuildData/build.db`. Apparently used to be solved by using `-UseModernBuildSystem=NO` in older Xcode. At least, the framework seems to build correctly.

**Comment by eskroch** [comment]
I'm able to do a successful build of the XCFramework target with no errors. I'm using the latest from the `release-2.4` branch. I've pushed a few updates to that branch over the last couple weeks, one of which made sure the dependency analysis setting is set correctly for all of the run script build phases.

Mac Studio M1 Max
macOS Ventura 13.1
Xcode 14.2

**Comment by richwaters** [comment]
FWIW, this issue was never fixed for me.  I can work around it by clicking File > Project Settings > Advanced and enabling the "Legacy" build location. Ultimately, I think the issue might be caused by some mismatch between the DerivedData default Xcode build location and the one specified by SYMROOT in generate_universal_xcframework.sh
